### ISSUE TITLE
When entering CH4 values for integrated the CH4 value could not be left blank. 

### ISSUE THREAD

**Issue by jgonz219** [landfill-eforms/landfill-android-app#3]
Doing integrated, I won't know the value until I return from the field and actually read the samples that I took.  I wound up putting dummy values in. (noted in e-mail 4/4/2017)

Should we leave this field blank/default value and only allow a change in desktop/webform?  Or we can leave a hint informing that that feild cannot be edited until back in the office.

**Comment by jgonz219** [comment]
double check with william

**Comment by William-Andrews** [comment]
In order to do the documenting of the start and end times and the grid, out in the field, I resorted to entering obvious dummy values (0.1) in the CH4 field.  Then after the sampling is complete and the reading is actual done (back at the 'office', but not near a PC, the equipment we use to get the reading is in a shed) I would edit the values to the actual.  It would be better to allow the field user to leave that blank and still record the entry.

**Comment by alvinquach** [comment]
Web app will have to be modified to allow IMPORTING null reading values.
