### ISSUE TITLE
Data entry validation error messages 

### ISSUE THREAD

**Issue by jgonz219** [landfill-eforms/landfill-android-app#9]
These should pop-up (fixed) and require an acknowledgement.  Otherwise it can be too brief.  They also should pop up as the user leaves a field in question.

**Comment by jgonz219** [comment]
needs Williams input

**Comment by William-Andrews** [comment]
Previous versions of the data validation errors pop-up faded too quickly and did not require an acknowledgement.   Often they could go unnoticed.   Also, rather than dropping to the next field, it should leave the focus in the field with an error.

Further, there was on the list of requests, entry confirmation for values above or below certain ranges that are not errors, but just concerns.

**Comment by aadame95** [comment]
have a notification as you leave the field of inputed value
